from sklearn.preprocessing import LabelEncoder

ALL_LABELS = [
    "BACKDOOR_MALWARE",
    "BENIGN",
    "BROWSERHIJACKING",
    "COMMANDINJECTION",
    "DDOS-ACK_FRAGMENTATION",
    "DDOS-HTTP_FLOOD",
    "DDOS-ICMP_FLOOD",
    "DDOS-ICMP_FRAGMENTATION",
    "DDOS-PSHACK_FLOOD",
    "DDOS-RSTFINFLOOD",
    "DDOS-SLOWLORIS",
    "DDOS-SYN_FLOOD",
    "DDOS-SYNONYMOUSIP_FLOOD",
    "DDOS-TCP_FLOOD",
    "DDOS-UDP_FLOOD",
    "DDOS-UDP_FRAGMENTATION",
    "DICTIONARYBRUTEFORCE",
    "DNS_SPOOFING",
    "DOS-HTTP_FLOOD",
    "DOS-SYN_FLOOD",
    "DOS-TCP_FLOOD",
    "DOS-UDP_FLOOD",
    "MITM-ARPSPOOFING",
    "MIRAI-GREETH_FLOOD",
    "MIRAI-GREIP_FLOOD",
    "MIRAI-UDPPLAIN",
    "RECON-HOSTDISCOVERY",
    "RECON-OSSCAN",
    "RECON-PINGSWEEP",
    "RECON-PORTSCAN",
    "SQLINJECTION",
    "UPLOADING_ATTACK",
    "VULNERABILITYSCAN",
    "XSS",
]

le = LabelEncoder()
le.fit(ALL_LABELS)

NUM_CLASSES  = len(ALL_LABELS)   # 34
NUM_FEATURES = 40
